logging:
  level:
    ru.yandex.practicum.commerce: TRACE
    org:
      springframework: ERROR
      springframework.cloud.netflix.eureka: INFO
      apache.kafka: WARN

server:
  port: 0

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/telemetry/{application}
            - classpath:config/commerce/{application}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/