spring:
  application:
    name: collector
  cloud:
    config:
      enabled: false
      fail-fast: false

eureka:
  client:
    enabled: false

grpc:
  server:
    port: 59091

collector:
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      properties:
        "bootstrap.servers": "localhost:9092"
        "key.serializer": "org.apache.kafka.common.serialization.StringSerializer"
        "value.serializer": "ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer"

logging:
  level:
    ru.yandex.practicum.telemetry: TRACE
    org:
      springframework: ERROR
