aggregator:
  kafka:
    bootstrap-server: localhost:9092
    producer:
      properties:
        "bootstrap.servers": ${aggregator.kafka.bootstrap-server}
        "key.serializer": org.apache.kafka.common.serialization.StringSerializer
      topic: telemetry.snapshot.v1

    consumer:
      properties:
        "bootstrap.servers": ${aggregator.kafka.bootstrap-server}
        "enable.auto.commit": false
        "group.id": telemetry.aggregator.sensors
        "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
      topic: telemetry.sensor.v1
      pool-timeout: 100ms