logging:
  level:
    ru.yandex.practicum.telemetry: TRACE
    org:
      springframework: ERROR
      springframework.cloud.netflix.eureka: INFO
      apache.kafka: WARN

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smarthome
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

analyzer:
  kafka:
    bootstrap-servers: "localhost:9092"
    hubs:
      topic: "telemetry.hub.v1"
      properties:
        "bootstrap.servers": ${analyzer.kafka.bootstrap-servers}
        "group.id": "analyzer-hubs-group"
        "auto.offset.reset": "earliest"
        "key.deserializer": "org.apache.kafka.common.serialization.StringDeserializer"
        "value.deserializer": "ru.yandex.practicum.kafka.deserializer.HubEventDeserializer"
    snapshots:
      topic: "telemetry.snapshot.v1"
      properties:
        "bootstrap.servers": ${analyzer.kafka.bootstrap-servers}
        "group.id": "analyzer-snapshots-group"
        "auto.offset.reset": "earliest"
        "key.deserializer": "org.apache.kafka.common.serialization.StringDeserializer"
        "value.deserializer": "ru.yandex.practicum.kafka.deserializer.SnapshotDeserializer"